#pragma once

constexpr auto CPP_GITIGNORE = 
                        "build\n"
                        "\n"
                        "# Prerequisites\n"
                        "*.d\n"
                        "\n"
                        "# Compiled Object files\n"
                        "*.slo\n"
                        "*.lo\n"
                        "*.o\n"
                        "*.obj\n"
                        "\n"
                        "# Precompiled Headers\n"
                        "*.gch\n"
                        "*.pch\n"
                        "\n"
                        "# Linker files\n"
                        "*.ilk\n"
                        "\n"
                        "# Debugger Files\n"
                        "*.pdb\n"
                        "\n"
                        "# Compiled Dynamic libraries\n"
                        "*.so\n"
                        "*.dylib\n"
                        "*.dll\n"
                        "\n"
                        "# Fortran module files\n"
                        "*.mod\n"
                        "*.smod\n"
                        "\n"
                        "# Compiled Static libraries\n"
                        "*.lai\n"
                        "*.la\n"
                        "*.a\n"
                        "*.lib\n"
                        "\n"
                        "# Executables\n"
                        "*.exe\n"
                        "*.out\n"
                        "*.app\n"
                        "\n";
