#pragma once

constexpr auto CODEQL_ACTION_BOILERPLATE = 
                    "# For most projects, this workflow file will not need changing; you simply need\n"
                    "# to commit it to your repository.\n"
                    "#\n"
                    "# You may wish to alter this file to override the set of languages analyzed,\n"
                    "# or to provide custom queries or build logic.\n"
                    "name: "CodeQL"\n"
                    "\n"
                    "on:\n"
                    "  push:\n"
                    "    branches: [master]\n"
                    "  pull_request:\n"
                    "    # The branches below must be a subset of the branches above\n"
                    "    branches: [master]\n"
                    "  schedule:\n"
                    "    - cron: '0 3 * * 6'\n"
                    "\n"
                    "jobs:\n"
                    "  analyze:\n"
                    "    name: Analyze\n"
                    "    runs-on: ubuntu-latest\n"
                    "\n"
                    "    strategy:\n"
                    "      fail-fast: false\n"
                    "      matrix:\n"
                    "        # Override automatic language detection by changing the below list\n"
                    "        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']\n"
                    "        language: ['cpp']\n"
                    "        # Learn more...\n"
                    "        # https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#overriding-automatic-language-detection\n"
                    "\n"
                    "    steps:\n"
                    "    - name: Checkout repository\n"
                    "      uses: actions/checkout@v2\n"
                    "      with:\n"
                    "        submodules: recursive\n"
                    "\n"
                    "    # Initializes the CodeQL tools for scanning.\n"
                    "    - name: Initialize CodeQL\n"
                    "      uses: github/codeql-action/init@v1\n"
                    "      with:\n"
                    "        languages: ${{ matrix.language }}\n"
                    "        # If you wish to specify custom queries, you can do so here or in a config file.\n"
                    "        # By default, queries listed here will override any specified in a config file.\n"
                    "        # Prefix the list here with "+" to use these queries and those in the config file.\n"
                    "        # queries: ./path/to/local/query, your-org/your-repo/queries@main\n"
                    "\n"
                    "    # Note: The AutoBuild step has been removed from here, as we are using other workflow for building\n"
                    "    \n"
                    "    - name: Perform CodeQL Analysis\n"
                    "      uses: github/codeql-action/analyze@v1\n"
                    "\n";
