#pragma once

constexpr auto CMAKE_WORKFLOW_BOILERPLATE =
                        "name: Build Status\n"
                        "\n"
                        "on: [push]\n"
                        "\n"
                        "env:\n"
                        "  BUILD_TYPE: Release\n"
                        "\n"
                        "jobs:\n"
                        "  build-ubuntu:\n"
                        "    runs-on: ubuntu-latest\n"
                        "    steps:\n"
                        "    - name: Checkout Repo\n"
                        "      uses: actions/checkout@v2\n"
                        "\n"
                        "    - name: Create build directory\n"
                        "      run: cmake -E make_directory build\n"
                        "\n"
                        "    - name: Configure\n"
                        "      working-directory: ${{github.workspace}}/build\n"
                        "      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE\n"
                        "\n"
                        "    - name: Build\n"
                        "      working-directory: ${{github.workspace}}/build\n"
                        "      run: cmake --build . --config $BUILD_TYPE\n"
                        "\n";

constexpr auto MAKE_WORKFLOW_BOILERPLATE =
                        "name: Build Status\n"
                        "\n"
                        "on: [push]\n"
                        "\n"
                        "jobs:\n"
                        "  build-ubuntu:\n"
                        "    runs-on: ubuntu-latest\n"
                        "    steps:\n"
                        "    - name: Checkout Repo\n"
                        "      uses: actions/checkout@v2\n"
                        "\n"
                        "    - name: Build\n"
                        "      run: make\n"
                        "\n";
