#pragma once

constexpr auto README_CMAKE_BOILERPLATE = 
                        "${{CPPROJ_PROJECT_NAME}}\n"
                        "----\n"
                        "\n"
                        "Have fun coding, put in your project's description here.\n"
                        "\n"
                        "## Dependencies\n"
                        "\n"
                        "To make development faster, the project used:\n"
                        "\n"
                        "## Building\n"
                        "\n"
                        "Required a compiler supporting C++${{CPPROJ_CXX_STANDARD}}\n"
                        "\n"
                        "```\n"
                        "mkdir build && cd build\n"
                        "cmake ..\n"
                        "cmake --build .\n"
                        "```\n"
                        "\n"
                        "## Future\n"
                        "\n"
                        "* Future scope of the project, OR your TODO list, that you may not be implementing now\n"
                        "\n"
                        ":copyright: Author ${{CPPROJ_YEAR}}\n"
                        "\n";

constexpr auto README_MAKE_BOILERPLATE = 
                        "${{CPPROJ_PROJECT_NAME}}\n"
                        "----\n"
                        "\n"
                        "Have fun coding, put in your project's description\n"
                        "\n"
                        "## Dependencies\n"
                        "\n"
                        "To make development faster, the project used:\n"
                        "\n"
                        "## Building\n"
                        "\n"
                        "Required a compiler supporting C++${{CPPROJ_CXX_STANDARD}}\n"
                        "\n"
                        "```\n"
                        "make"
                        "```\n"
                        "> Add more relevant commands according to your project\n"
                        "\n"
                        "## Future\n"
                        "\n"
                        "* Future scope of the project, OR your TODO list, that you may not be implementing now\n"
                        "\n"
                        ":copyright: Author ${{CPPROJ_YEAR}}\n"
                        "\n";
