name: Build Status

on: [push, pull_request]

env:
  SAMPLE_PROJ: new_proj

# Ubuntu latest build fail, since it can't find <filesystem>, even though C++17 standard
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: make

    - name: Create sample repo
      run: ./cpproj ${{SAMPLE_PROJ}}

    - name: Build and run sample repo
      working-directory: ${{github.workspace}}/${{SAMPLE_PROJ}}
      run: ../cpproj --run && cd build && ../cpproj --run
