name: Build Status

on: [push, pr]

env:
  BUILD_TYPE: Release
  SAMPLE_PROJ: new_proj

# Ubuntu latest build fail, since it can't find <filesystem>, even though C++17 standard
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOMPILE_OPTIONS=-lstdc++fs

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: sudo cmake --install .

    - name: Create sample repo
      working-directory: ${{github.workspace}}/build/
      run: ./cpproj $SAMPLE_PROJ

    - name: Build and run sample repo
      working-directory: ${{github.workspace}}/build/$SAMPLE_PROJ
      run: ../cpproj --run && cd build && ../cpproj --run
