name: Windows Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  SAMPLE_PROJ: new_proj

# Ubuntu latest build fail, since it can't find <filesystem>, even though C++17 standard
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Create sample repo
      working-directory: ${{github.workspace}}/build/${{BUILD_TYPE}}
      run: .\cpproj ${{SAMPLE_PROJ}}

    - name: Build and run sample repo
      working-directory: ${{github.workspace}}/build/${{BUILD_TYPE}}/${{SAMPLE_PROJ}}
      run: ..\cpproj --run && cd build && ..\cpproj --run
